file(GLOB_RECURSE PLATFORM_SOURCES ${CMAKE_CURRENT_LIST_DIR}/${BOARD}/*.c )
set(PLATFORM_INCLUDES ${CMAKE_CURRENT_LIST_DIR}/${BOARD})
set(PLATFORM_COMPILE_FLAGS ${CMAKE_CURRENT_LIST_DIR}/${BOARD}/${BOARD}.xn)
